language: csharp

script:
  - xbuild /p:Configuration=Debug csharp6-libraries.sln

before_install:
  - sudo apt-get install nunit-console

before_script:
  - nuget restore csharp6-libraries.sln

after_script:
  - nunit-console Collections.Tests/bin/Debug/Collections.Tests.dll