
language: csharp

script:
  - xbuild /p:Configuration=Debug csharp6-microlibraries.sln

before_install:
  - sudo apt-get install nunit-console

before_script:
  - nuget restore csharp6-microlibraries.sln

after_script:
  - nunit-console artifacts/debug/tests/collections/ml.map.tests/ML.Map.Tests.dll
  - nunit-console artifacts/debug/tests/collections/ml.set.tests/ML.Set.Tests.dll
  - nunit-console artifacts/debug/tests/collections/ml.stack.tests/ML.Stack.Tests.dll