language: csharp
solution: ./csharp6-libraries.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ./csharp6-libraries.sln
 
script:
  - xbuild ./csharp6-libraries.sln
  - nunit-console ./Collections.Tests/bin/Debug/Collections.Tests.dll
  
after_success:
  - bash <(curl -s https://codecov.io/bash)